apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openhandsOperator.fullname" . }}
  labels:
    {{- include "openhandsOperator.labels" . | nindent 4 }}
data:
  LOG_LEVEL: "{{ .Values.logLevel }}"
  {{- range $idx, $val := .Values.operator.watchNamespaces }}
  JAVAOPERATORSDK_RECONCILERS_LLMTASKRECONCILER_{{ $idx }}: "{{ $val }}"
  {{- end }}
